name = "gold-price-backend"
main = "src/index.ts"
compatibility_date = "2024-10-05"
workers_dev = true
compatibility_flags = [ "nodejs_compat" ]

[vars]
GOLD_API_KEY = "7d1ab35c91d23dec7f509b342e925f28"
BACKEND_URL = "http://localhost:3000/api/v1"
#BACKEND_URL = "https://amaraah-server.vercel.app/api/v1/"

[triggers]
crons = ["14 22 * * *"] 

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1